name: 'Deploy Azure Resource'

inputs:
  az_rg_n:
    description: “Azure ResourceGroup name”
    required: true
  sql_admin_login:
    description: "test sql admin login"
    required: true
  sql_admin_password:
    description: "test sql password login"
    required: true

runs:
  using: 'composite'
  steps:
  - name: test-bicep-file-deployment
    uses: azure/arm-deploy@v1
    with:
      scope: resourcegroup
      resourceGroupName: ${{ inputs.az_rg_n }}
      deploymentMode: Complete
      template: examples/examples.bicep
      parameters: sql_admin_login=${{ inputs.sql_admin_login }} sql_admin_password=${{ inputs.sql_admin_password }}
      failOnStdErr: true